import type { Metadata } from "next";
import "./styles/globals.css";
import Navbar from './components/Navbar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Frontend for drizzle-starter</title>
      </head>
      <body>
        <Navbar />
        { children }
      </body>
    </html>
  );
}
